[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
# runner = 'riscv64-unknown-elf-gdb -x ../../openocd.gdb'
runner = "probe-rs run --chip HPM5361 --protocol jtag --chip-description-path HPMicro.yaml --speed 20000000 --probe 0d28:0204:0000008000066a02045ac61b0000034c0000000097969921"
# runner = "probe-rs run --chip HPM5361 --protocol jtag"

rustflags = [
    # Target features:
    # The default for imacf is is "+m,+a,+c,+f"
    # "-C",
    # "target-feature=+d,+zba,+zbb,+zbc,+zbs",
    # # Linker scripts:
    # "-C",
    # "link-arg=-Tmemory.x",
    # "-C",
    # "link-arg=-Tdevice.x", # __VECTORED_INTERRUPTS
    # "-C",
    # "link-arg=-Tlink-fixed.x",
    # "-C",
    # "link-arg=-Tdefmt.x",
    # "-C",
    # "link-arg=-nmagic",

    # "--emit", "obj",
    # "--emit", "asm",
]

[unstable]
build-std = ["core", "alloc"]

[env]
DEFMT_LOG = "info"
